name: Build and Release Alazkar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: alazkar  # السطر ده هو "العلاج" اللي هيخليه يدخل للمجلد الصح
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: azkar-app-apk
          path: alazkar/build/app/outputs/flutter-apk/app-release.apk # تأكدنا إن المسار هنا برضه بيبدأ بـ alazkar
